Repository FC-Chilli-Bubble/front-officener, pull requests merged in 2023-09, with the labels that each got.

#6 💄 Design: 공통 Header 컴포넌트
  src/App.tsx
  src/assets/ico_back.svg
  src/assets/ico_close.svg
  src/components/Common/Header.tsx
  src/constants/commonUiData.ts
  src/pages/Home/Home.tsx
  tsconfig.json
Labels: 🎨 Html&css, 🐞 BugFix

#9 [Style] 공통 Layout 모바일 최적화 긴급 반영
  .eslintrc.cjs
  .prettierrc
  src/assets/ico_delivery.svg
  src/assets/ico_delivery_off.svg
  src/assets/ico_home.svg
  src/assets/ico_home_off.svg
  src/assets/ico_more.svg
  src/assets/ico_my.svg
  src/assets/ico_my_off.svg
  src/components/Common/BottomNavigation.tsx
  src/components/Common/Button.tsx
  src/components/Common/Header.tsx
  src/components/Common/Layout.tsx
  src/components/Common/NavLayout.tsx
  src/components/Home/HomeHeader.tsx
  src/constants/commonUiData.ts
  src/pages/Home/Home.tsx
  src/styles/theme.ts
  src/utils/Router.tsx
Labels: 🎨 Html&css

#10 Feature/common UI
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/assets/ico_check.svg
  src/assets/ico_error.svg
  src/assets/ico_red_error.svg
  src/assets/ico_search.svg
  src/assets/ico_wrong.svg
  src/components/Common/BottomNavigation.tsx
  src/components/Common/Button.tsx
  src/components/Common/FormField.tsx
  src/components/Common/Header.tsx
  src/components/Common/Modal.tsx
  src/components/Common/NavLayout.tsx
  src/components/Common/OutlineButton.tsx
  src/components/Common/OutlineTag.tsx
  src/components/Common/SearchInput.tsx
  src/components/Common/SelectedInput.tsx
  src/components/Common/Tag.tsx
  src/constants/commonUiData.ts
  src/constants/modalDatas.ts
  src/hooks/useModal.ts
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/Register/Register.tsx
  src/states/modalAtom.ts
  src/states/tagAtom.ts
  src/stores/index.ts
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
  src/types/TModal.ts
  src/types/TTags.ts
  src/utils/Router.tsx
  tsconfig.json
Labels: ⚙ Setting, 🎨 Html&css

#12 Feature/home
  src/assets/ico_bell_w.svg
  src/assets/ico_right_arrow_g.svg
  src/assets/menus/ico_bill.svg
  src/assets/menus/ico_building_info.svg
  src/assets/menus/ico_car_manage.svg
  src/assets/menus/ico_elevator.svg
  src/assets/menus/ico_inconvenience.svg
  src/assets/menus/ico_office_info.svg
  src/assets/menus/ico_pass.svg
  src/assets/menus/ico_restaurant.svg
  src/assets/menus/ico_survey.svg
  src/assets/menus/ico_use_guide.svg
  src/components/Home/HomeHeader.tsx
  src/constants/commonUiData.ts
  src/constants/serviceMenus.ts
  src/pages/Home/Home.tsx
  src/pages/Home/HomeEx.tsx
  src/styles/theme.ts
Labels: 🎨 Html&css, ✨ Feature

#14 [Feat] 함께배달 글쓰기 화면 UI 작업 반영
  package-lock.json
  package.json
  src/assets/ico_chevron_down.svg
  src/components/Common/BottomSheetModal.tsx
  src/components/Common/Button.tsx
  src/components/Common/FormField.tsx
  src/components/Common/Header.tsx
  src/components/Common/Modal.tsx
  src/components/Common/OutlineButton.tsx
  src/components/Delivery/PostStep1.tsx
  src/components/Delivery/PostStep2.tsx
  src/components/Delivery/TagList.tsx
  src/components/Delivery/TimePicker.tsx
  src/constants/commonUiData.ts
  src/constants/modalDatas.ts
  src/constants/pickerData.ts
  src/pages/Delivery/DeliveryPost.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/HomeEx.tsx
  src/pages/Login/Login.tsx
  src/states/postAtom.ts
  src/states/postTagAtom.ts
  src/states/timePickerAtom.ts
  src/styles/theme.ts
  src/types/Delivery/IDeliveryPostRequest.ts
  src/utils/Router.tsx
Labels: 🎨 Html&css, ✨ Feature

#17 Featur/login
  src/apis/dummy_LoignAPI.ts
  src/components/Common/FormField.tsx
  src/components/Common/Header.tsx
  src/constants/regexp.ts
  src/pages/Login/Login.tsx
  src/pages/Login/LoginEx.tsx
  src/pages/Register/Intro.tsx
  src/pages/Register/Register.tsx
  src/types/TLogin.ts
  src/utils/Router.tsx
Labels: 🎨 Html&css, ✨ Feature

#18 [Feat] Mypage UI 작업 반영
  src/assets/ico_bell_w.svg
  src/assets/ico_chevron_right.svg
  src/assets/img_profile.svg
  src/components/MyPage/MyPageMenu.tsx
  src/components/MyPage/ProfileItem.tsx
  src/constants/commonUiData.ts
  src/constants/modalDatas.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyProfile.tsx
  src/styles/theme.ts
  src/utils/Router.tsx
Labels: 🎨 Html&css

#20 [Feat] 알림 화면 UI 작업 반영
  src/components/Home/HomeHeader.tsx
  src/components/Notification/NotificationItem.tsx
  src/pages/Notification/DummyNotifications.ts
  src/pages/Notification/Notification.tsx
  src/styles/GlobalStyles.ts
  src/utils/Router.tsx
Labels: 🎨 Html&css

#26 [Fix] 공통 모달 이슈 수정
  src/components/Common/Modal.tsx
  src/types/TModal.ts
Labels: 🐞 BugFix

#24 Feature/elevator UI
  src/assets/icon_elevatorDown.svg
  src/assets/icon_elevatorStop.svg
  src/assets/icon_elevatorUp.svg
  src/components/Elevator/ChoiceCard.tsx
  src/components/Elevator/FloorList.tsx
  src/components/Elevator/MissingCard.tsx
  src/constants/commonUiData.ts
  src/pages/Elevator/Dummydata.ts
  src/pages/Elevator/ElevatorHome.tsx
  src/states/floorAtom.ts
  src/utils/Router.tsx
Labels: 🎨 Html&css

#27 Feature/chat UI
  package-lock.json
  package.json
  src/apis/dummy_ChatAPI.ts
  src/assets/chatrooms/ico_alarm.svg
  src/assets/chatrooms/ico_checkBlue.svg
  src/assets/chatrooms/ico_copy.svg
  src/assets/chatrooms/ico_send.svg
  src/assets/chatrooms/ico_won.svg
  src/assets/chatrooms/ico_wonGreen.svg
  src/assets/ico_user.svg
  src/assets/ico_userimg.svg
  src/components/ChatRoom/ChatAlert.tsx
  src/components/ChatRoom/ChatBubble.tsx
  src/components/ChatRoom/ChatBubbleRender.tsx
  src/components/ChatRoom/ChatDeclarationBotomSheet.tsx
  src/components/ChatRoom/ChatDeclarationStep1.tsx
  src/components/ChatRoom/ChatDeclarationStep2.tsx
  src/components/ChatRoom/ChatDeclarationStep3.tsx
  src/components/ChatRoom/ChatFunctions.ts
  src/components/ChatRoom/ChatHeader.tsx
  src/components/ChatRoom/ChatInput.tsx
  src/components/ChatRoom/ChatProfile.tsx
  src/components/ChatRoom/ChatProfileModal.tsx
  src/components/Common/Modal.tsx
  src/constants/chatRoomModalData.ts
  src/constants/declarationCategory.ts
  src/pages/ChatRoom/ChatRoom.tsx
  src/states/chatDeclarationAtom.ts
  src/styles/theme.ts
  src/utils/Router.tsx
Labels: 🎨 Html&css, ✨ Feature

#23 Featur/signup
  src/assets/ico_arrow.svg
  src/assets/ico_blue_arrow.svg
  src/assets/ico_building.svg
  src/assets/ico_checkbox.svg
  src/assets/ico_gray_error.svg
  src/assets/ico_green_check.svg
  src/components/Common/Button.tsx
  src/components/Common/FormField.tsx
  src/components/Common/FormFieldButton.tsx
  src/components/Common/SearchButton.tsx
  src/components/Delivery/PostStep1.tsx
  src/components/Signup/CheckList.tsx
  src/components/Signup/SignupStep1.tsx
  src/components/Signup/SignupStep2.tsx
  src/components/Signup/SignupStep3.tsx
  src/components/Signup/SignupStep4.tsx
  src/components/Signup/SignupStep5.tsx
  src/components/Signup/SignupStep6.tsx
  src/components/Signup/SignupStep7.tsx
  src/components/Signup/buildingData.ts
  src/constants/commonUiData.ts
  src/pages/Login/Login.tsx
  src/pages/Register/Intro.tsx
  src/pages/Register/Register.tsx
  src/pages/Signup/Intro.tsx
  src/pages/Signup/SignupTest.tsx
  src/pages/Signup/Singup.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
  src/utils/Router.tsx
Labels: 🎨 Html&css

#28 Feature/deliverymainpage
  .eslintrc.cjs
  package-lock.json
  package.json
  src/apis/foodApi.ts
  src/assets/food/Group.svg
  src/assets/food/IMG1234.svg
  src/assets/food/IMG2345.svg
  src/assets/food/Rectangle 477-1.svg
  src/assets/food/Rectangle 477.svg
  src/assets/food/Rectangle 487-1.svg
  src/assets/food/Rectangle 487-2.svg
  src/assets/food/Rectangle 487-3.svg
  src/assets/food/Rectangle 487.svg
  src/assets/food/Rectangle 496.svg
  src/assets/food/Time.svg
  src/assets/food/Vector.svg
  src/assets/food/icon_alarm.svg
  src/components/Common/NavLayout.tsx
  src/components/Delivery/ChatItem.tsx
  src/components/Delivery/FoodItem.tsx
  src/components/Delivery/Header.tsx
  src/components/Delivery/MenuContent.tsx
  src/components/Delivery/OrderList.tsx
  src/components/Delivery/TogetherDelivery.tsx
  src/components/Delivery/TopMenu.tsx
  src/components/Details/DeleteModal.tsx
  src/components/Details/FoodItem.tsx
  src/components/Details/FooterButtons.tsx
  src/components/Details/Header.tsx
  src/components/Details/HostInfo.tsx
  src/components/Details/PhotoCard.tsx
  src/pages/Delivery/DeliveryPost.tsx
  src/pages/Deliverypage/DeliveryPage.tsx
  src/pages/Deliverypage/DetailsPage.tsx
  src/pages/Deliverypage/dummyData.ts
  src/utils/Router.tsx
Labels: 🎨 Html&css

#30 Feature/Signup : 회원가입 영역 Button공통컴포넌트 마진값삭제
  src/components/Common/Button.tsx
  src/components/Signup/SignupStep1.tsx
  src/components/Signup/SignupStep2.tsx
  src/components/Signup/SignupStep3.tsx
  src/components/Signup/SignupStep4.tsx
  src/components/Signup/SignupStep5.tsx
  src/components/Signup/SignupStep6.tsx
Labels: 🎨 Html&css, 🐞 BugFix

#31 [Feat] Axios 세팅 및 PWA 세팅
  index.html
  package-lock.json
  package.json
  public/icons/favicon-16x16.png
  public/icons/favicon-196x196.png
  public/icons/favicon-32x32.png
  public/icons/favicon.ico
  public/icons/logo-152x152.png
  public/icons/logo-512x512.png
  public/manifest.json
  src/App.tsx
  src/apis/apiClient.ts
  src/apis/index.ts
  src/components/Details/FoodItem.tsx
  src/components/Details/FooterButtons.tsx
  src/components/Details/Header.tsx
  src/components/Details/HostInfo.tsx
  src/components/Details/PhotoCard.tsx
  src/hooks/useAxiosInterceptor.tsx
  src/pages/Deliverypage/DetailsPage.tsx
  src/pages/Deliverypage/dummyData.ts
  src/pages/Home/Home.tsx
  src/types/Common/IErrorResponse.ts
  src/utils/Router.tsx
  sw.js
Labels: ⚙ Setting, 🎨 Html&css, 🐞 BugFix

#37 ⚙️ Chore: github actions setting
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#38 Fix/common UI
  src/assets/ico_delivery.svg
  src/assets/ico_delivery_off.svg
  src/assets/ico_home.svg
  src/assets/ico_home_off.svg
  src/assets/ico_my.svg
  src/assets/ico_my_off.svg
  src/assets/img_profile.svg
  src/components/Common/BottomNavigation.tsx
  src/components/Common/BottomSheetModal.tsx
  src/components/Common/NavLayout.tsx
  src/components/Delivery/TimePicker.tsx
  src/styles/GlobalStyles.ts
Labels: 🎨 Html&css, 🐞 BugFix

#41 Fix/delivery, detailsPage UI 수정
  src/assets/food/img_delivery_bg.svg
  src/assets/food/img_delivery_header.svg
  src/assets/food/img_details_bg.svg
  src/assets/food/postbutton.svg
  src/components/Delivery/FoodItem.tsx
  src/components/Delivery/Header.tsx
  src/components/Delivery/OrderList.tsx
  src/components/Delivery/PostStepStoreInfo.tsx
  src/components/Delivery/TopMenu.tsx
  src/components/Details/FoodItem.tsx
  src/components/Details/Header.tsx
  src/components/Details/HostInfo.tsx
  src/components/Details/PhotoCard.tsx
  src/pages/Deliverypage/DeliveryPage.tsx
  src/pages/Deliverypage/DetailsPage.tsx
Labels: 🐞 BugFix

#42 [Fix] UI 이슈 수정
  src/assets/ico_my_off.svg
  src/components/Delivery/OrderList.tsx
  src/components/Delivery/TogetherDelivery.tsx
  src/components/Details/HostInfo.tsx
  src/pages/Deliverypage/DeliveryPage.tsx
Labels: 🎨 Html&css, 🐞 BugFix

#43 Fix/signup
  package-lock.json
  src/assets/ico_arrow.svg
  src/assets/ico_blue_arrow.svg
  src/assets/ico_error.svg
  src/assets/ico_gray_arrow.svg
  src/components/Common/FormField.tsx
  src/components/Common/SelectedInput.tsx
  src/components/Signup/CheckList.tsx
  src/components/Signup/SignupStep1.tsx
  src/components/Signup/SignupStep2.tsx
  src/components/Signup/SignupStep3.tsx
  src/components/Signup/SignupStep4.tsx
  src/components/Signup/SignupStep5.tsx
  src/components/Signup/SignupStep6.tsx
  src/components/Signup/SignupStep7.tsx
  src/components/Signup/buildingData.ts
  src/constants/commonUiData.ts
  src/pages/Login/Login.tsx
  src/pages/Signup/Intro.tsx
  src/pages/Signup/Singup.tsx
Labels: 🎨 Html&css, 🐞 BugFix

#50 [Feat] Axios 서버 환경 설정
  src/apis/Delivery/deliveryPostRequests.ts
  src/apis/apiClient.ts
  src/pages/Delivery/DeliveryPost.tsx
  src/types/Common/ICommonResponse.ts
  src/types/Delivery/IBank.ts
Labels: ⚙ Setting, 📬 API

#44 Fix/chat UI
  package-lock.json
  src/apis/dummy_ChatAPI.ts
  src/assets/chatrooms/ico_checkWhite.svg
  src/assets/chatrooms/ico_wonWhite.svg
  src/components/ChatRoom/ChatBubble/ChatAlert.tsx
  src/components/ChatRoom/ChatBubble/ChatBubble.tsx
  src/components/ChatRoom/ChatBubble/ChatBubbleRender.tsx
  src/components/ChatRoom/ChatDeclaration/ChatDeclarationBotomSheet.tsx
  src/components/ChatRoom/ChatDeclaration/ChatDeclarationStepCategory.tsx
  src/components/ChatRoom/ChatDeclaration/ChatDeclarationStepDetail.tsx
  src/components/ChatRoom/ChatDeclaration/ChatDeclarationStepFinal.tsx
  src/components/ChatRoom/ChatFunctions.ts
  src/components/ChatRoom/ChatHeader/ButtonTitleGuest.tsx
  src/components/ChatRoom/ChatHeader/ChatHeader.tsx
  src/components/ChatRoom/ChatInput.tsx
  src/components/ChatRoom/ChatProfile/ChatProfile.tsx
  src/components/ChatRoom/ChatProfile/ChatProfileModal.tsx
  src/components/Common/BottomSheetModal.tsx
  src/components/Common/Button.tsx
  src/components/Common/Modal.tsx
  src/components/Details/DeleteModal.tsx
  src/constants/chatRoomModalData.ts
  src/pages/ChatRoom/ChatRoom.tsx
  src/states/chatInputFocusAtom.ts
Labels: 🐞 BugFix

#55 [Feat] 함께배달 글 등록 기능 연동
  src/apis/Delivery/deliveryPostRequests.ts
  src/components/Common/Modal.tsx
  src/components/Delivery/PostStepDeliveryInfo.tsx
  src/components/Delivery/PostStepStoreInfo.tsx
  src/components/Delivery/TagList.tsx
  src/components/Delivery/TimePicker.tsx
  src/constants/banks.ts
  src/constants/commonUiData.ts
  src/constants/modalDatas.ts
  src/pages/Delivery/DeliveryPost.tsx
  src/states/postAtom.ts
  src/types/Common/ICommonResponse.ts
  src/types/Delivery/IBank.ts
  src/types/Delivery/IDeliveryPostRequest.ts
Labels: 📬 API, ✨ Feature

#58 Fix/signup 로그인API 연동
  package-lock.json
  src/App.tsx
  src/apis/Login/LoginRequests.ts
  src/apis/Signup/AuthCodeRequests.ts
  src/apis/Signup/CodeConfirmRequests.ts
  src/apis/Signup/SignupRequests.ts
  src/apis/Signup/buildingSearchRequests.ts
  src/apis/Signup/building_dummy_Data.ts
  src/components/Signup/SignupStep3.tsx
  src/constants/regexp.ts
  src/hooks/useAxiosInterceptor.tsx
  src/pages/Login/Login.tsx
  src/states/userDataAtom.ts
  src/types/Login/ILogin.ts
  src/types/Login/IUser.ts
  src/types/Signup/IAuth.ts
  src/types/Signup/IBuilding.ts
  src/types/Signup/IConfirm.ts
  src/types/Signup/ISignup.ts
  src/types/TTags.ts
Labels: 📬 API

#62 [Feat] 함께배달 게시글 관련 기능 반영
  .eslintrc.cjs
  .github/workflows/deploy.yml
  index.html
  src/apis/Delivery/deliveryDetailRequests.ts
  src/apis/Delivery/deliveryPostRequests.ts
  src/components/Common/FormField.tsx
  src/components/Delivery/FoodItem.tsx
  src/components/Delivery/PostStepStoreInfo.tsx
  src/components/Delivery/TimePicker.tsx
  src/components/Details/DeleteModal.tsx
  src/components/Details/FooterButtons.tsx
  src/components/Details/HostInfo.tsx
  src/components/Details/MenuLinkCard.tsx
  src/components/Details/StoreInfo.tsx
  src/constants/banks.ts
  src/constants/modalDatas.ts
  src/hooks/useAxiosInterceptor.tsx
  src/pages/Delivery/DeliveryPost.tsx
  src/pages/Deliverypage/DetailsPage.tsx
  src/types/Delivery/IBank.ts
  src/types/Delivery/IDeliveryPost.ts
  src/utils/Router.tsx
  sw.js
Labels: 📬 API, ✨ Feature

#66 [Fix]:로그인 인증 에러 처리 : 토큰만료401
  src/App.tsx
  src/constants/modalDatas.ts
  src/hooks/useAxiosInterceptor.tsx
  src/main.tsx
  src/pages/Login/Login.tsx
Labels: 🐞 BugFix

#65 [Feat] 함께배달 참여 요청 기능 연동
  public/manifest.json
  src/apis/Delivery/deliveryDetailRequests.ts
  src/components/Delivery/FoodItem.tsx
  src/constants/modalDatas.ts
  src/pages/Deliverypage/DetailsPage.tsx
Labels: 📬 API, ✨ Feature

#68 [Feat] 로그인 한 사용자 정보 노출
  src/App.tsx
  src/hooks/useAxiosInterceptor.tsx
  src/pages/Home/Home.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyProfile.tsx
Labels: ✨ Feature

#69 Feature/elevator 엘리베이터 메인페이지 API 연동
  dist/assets/Rectangle 487-054adfa3.svg
  dist/assets/Rectangle 496-348b04e9.svg
  dist/assets/Time-b7541e45.svg
  dist/assets/ico_alarm-53e1aa04.svg
  dist/assets/ico_back-13205113.svg
  dist/assets/ico_bell_w-d3393683.svg
  dist/assets/ico_bill-0c986366.svg
  dist/assets/ico_building-b7b3de57.svg
  dist/assets/ico_building_info-6d466246.svg
  dist/assets/ico_car_manage-29503ac9.svg
  dist/assets/ico_check-a007d360.svg
  dist/assets/ico_chevron_down-5e83d90e.svg
  dist/assets/ico_chevron_right-e4f6a1a2.svg
  dist/assets/ico_close-7378c19a.svg
  dist/assets/ico_copy-5ec3bf7a.svg
  dist/assets/ico_delivery-67ab9d4a.svg
  dist/assets/ico_delivery_off-a6db1623.svg
  dist/assets/ico_elevator-29508b92.svg
  dist/assets/ico_green_check-09ca0252.svg
  dist/assets/ico_home-d82f3d05.svg
  dist/assets/ico_home_off-8e7102ed.svg
  dist/assets/ico_inconvenience-59cfde45.svg
  dist/assets/ico_more-2ed43e53.svg
  dist/assets/ico_my-684afd77.svg
  dist/assets/ico_office_info-2846c4c6.svg
  dist/assets/ico_pass-f4ff1b20.svg
  dist/assets/ico_red_error-d0b09b51.svg
  dist/assets/ico_restaurant-aaa7f417.svg
  dist/assets/ico_right_arrow_g-89bcd309.svg
  dist/assets/ico_search-270ddcc1.svg
  dist/assets/ico_send-e0c88cfa.svg
  dist/assets/ico_survey-effaa22a.svg
  dist/assets/ico_use_guide-f09c19cb.svg
  dist/assets/ico_user-1fdc8143.svg
  dist/assets/ico_won-3d33db87.svg
  dist/assets/ico_wonGreen-7e7b0d66.svg
  dist/assets/ico_wrong-a75735a3.svg
  dist/assets/icon_alarm-4ee5d49f.svg
  dist/assets/icon_elevatorDown-188a96f7.svg
  dist/assets/icon_elevatorStop-22061f50.svg
  dist/assets/icon_elevatorUp-ec9d675a.svg
  dist/assets/img_profile-ba0e1b7b.svg
  dist/icons/favicon-16x16.png
  dist/icons/favicon-196x196.png
  dist/icons/favicon-32x32.png
  dist/icons/favicon.ico
  dist/icons/logo-152x152.png
  dist/icons/logo-512x512.png
  dist/index.html
  dist/manifest.json
  dist/vite.svg
  src/apis/Elevator/elevatorGetRequests.ts
  src/components/Elevator/ChoiceCard.tsx
  src/pages/Elevator/ElevatorHome.tsx
  src/types/Elevator/IElevator.ts
Labels: 📬 API
